version: "3.8"

services:
  client:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: stats-bot
    command: yarn dev
    ports:
      - "5050:5050"
    volumes:
      - ./:/app/
    networks:
      - pr-server_network

networks:
  pr-server_network:
    name: pr-server-network
    external: true
